services:
  worker_flow:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
      args:
        APP: worker_flow
        PORT: ${WORKER_FLOW_PORT}
      target: ${TARGET:-debug}
    container_name: worker_flow
    restart: always
    volumes:
      - "../../:/app"
    env_file:
      - ${ENV_FILE:-../../.env}
    environment:
      - APP=worker_flow
    ports:
      - ${WORKER_FLOW_PORT}:${WORKER_FLOW_PORT}
      - 2345:2345
    networks:
      - core
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  worker_post:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
      args:
        APP: worker_post
        PORT: ${WORKER_POST_PORT}
      target: ${TARGET:-debug}
    container_name: worker_post
    restart: always
    volumes:
      - "../../:/app"
    env_file:
      - ${ENV_FILE:-../../.env}
    environment:
      - APP=worker_post
    ports:
      - ${WORKER_POST_PORT}:${WORKER_POST_PORT}
      - 2346:2345
    networks:
      - core
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  core:
    driver: bridge
