services:
  worker-flow:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
    container_name: worker-flow
    ports:
      - "8080:8080"
    environment:
      - WORKER_FLOW_PORT=8080
    working_dir: /workspace/services/worker_flow
    command: ["air"]
    volumes:
      - ../../:/workspace
    networks:
      - microservices
    restart: unless-stopped
  
  worker-post:
    build:
      context: ../../
      dockerfile: devops/docker/Dockerfile
    container_name: worker-post
    ports:
      - "8081:8081"
    environment:
      - WORKER_POST_PORT=8081
    working_dir: /workspace/services/worker_post
    command: ["air"]
    volumes:
      - ../../:/workspace
    networks:
      - microservices
    restart: unless-stopped

networks:
  microservices:
    driver: bridge
